
/*
 * COPYRIGHT 1992 SAMUEL H. SMITH
 * ALL RIGHTS RESERVED
 *
 * THIS DOCUMENT CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS
 * PROPRIETARY TO SAMUEL H. SMITH DBA THE TOOL SHOP.
 *
 */

/* HDKTYPES.H - HS/LINK DEVELOPER KIT - DEFINE COMMON DATA TYPES */

#ifndef HDK_TYPES

typedef unsigned char uchar;            /* unsigned characters */

typedef unsigned int block_number;      /* block within current file */

typedef unsigned int user_number;           /* user registration numbers */

typedef unsigned long hs_clock_t;                   /* bios clock (seconds since midnight) */

#define HDK_TYPES
#endif

